
diccionario_individual = {
    "H15": {
        "Sí": 1,
        "No": 2,
    },
    "ANO4": "año de relevamiento",
    "TRIMESTRE": {
        "1er. Trimestre": 1,
        "2do. Trimestre": 2,
        "3er. Trimestre": 3,
        "4to. Trimestre": 4,
    },
    "REGION": {
        "Gran Buenos Aires": 1,
        "NOA": 40,
        "NEA": 41,
        "Cuyo": 42,
        "Pampeana": 43,
        "Patagónica": 44,
    },
    "MAS_500": {
        "N": 0,
        "S": 1,
        "Ns./Nr.": 9,
    },
    "AGLOMERADO" : {
        "Gran La Plata" : 2,
        "Bahía Blanca - Cerri" : 3,
        "Gran Rosario" : 4,
        "Gran Santa Fé" : 5,
        "Gran Paraná" : 6,
        "Posadas" : 7,
        "Gran Resistencia" : 8,
        "Cdro. Rivadavia – Rada Tilly" : 9,
        "Gran Mendoza" : 10,
        "Corrientes" : 12,
        "Gran Córdoba" : 13,
        "Concordia" : 14,
        "Formosa" : 15,
        "Neuquén – Plottier" : 17,
        "S.del Estero - La Banda" : 18,
        "Jujuy - Palpalá" : 19,
        "Río Gallegos" : 20,
        "Gran Catamarca" : 22,
        "Salta" : 23,
        "La Rioja" : 25,
        "San Luis - El Chorrillo" : 26,
        "Gran San Juan" : 27,
        "Gran Tucumán - T. Viejo" : 29,
        "Santa Rosa - Toay" : 30,
        "Ushuaia - Río Grande" : 31,
        "Ciudad de Buenos Aires" : 32,
        "Partidos del GBA" : 33,
        "Mar del Plata - Batán" : 34,
        "Río Cuarto" : 36,
    },
    "CH03": {
        "Jefe" : int("01"),
        "Cónyuge/Pareja" : int("02"),
        "Hijo/Hijastro" : int("03"),
        "Yerno/Nuera" : int("04"),
        "Nieto" : int("05"),
        "Madre/Padre" : int("06"),
        "Suegro" : int("07"),
        "Hermano" : int("08"),
        "Otros familiares" : int("09"),
        "No familiares" : int("10"),
    },
    "CH04": {
        "Varón" : 1,
        "Mujer" : 2,
    },
    "CH07": {
        "Unido" : int("1"),
        "Casado" : int("2"),
        "Separadoo o divorciado" : int("3"),
        "Viudo" : int("4"),
        "Soltero" : int("5"),
    },
    "CH08": {
        "Obra social (incluye PAMI)" : int("1"),
        "Mutual / Prepaga / Servicio de emergencia" : int("2"),
        "Planes y seguros públicos" : int("3"),
        "No paga ni le descuentan" : int("4"),
        "Ns./Nr." : int("9"),
        "Obra social y mutual / prepaga / servicio de emergencia" : int("12"),
        "Obra social y Planes y Seguros Públicos" : int("13"),
        "Mutual / prepaga / servicio de emergencia / Planes y Seguros Públicos" : int("23"),
        "Obra social, mutual / prepaga / servicio de emergencia y Planes y Seguros Públicos" : int("123"),
    },
    "CH09": {
        "Sí" : int("1"),
        "No" : int("2"),
        "Menor de 2 años" : int("3"),
    },
    "CH10": {
        "Sí, asiste" : int("1"),
        "No asiste, pero asistió" : int("2"),
        "Nunca asistió" : int("3"),
    },
    "CH11": {
        "Público" : int("1"),
        "Privado" : int("2"),
        "Ns./Nr." : int("9"),
    },
    "CH12": {
        "Jardín/ Preescolar" : int("1"),
        "Primario" : int("2"),
        "EGB" : int("3"),
        "Secundario" : int("4"),
        "Polimodal" : int("5"),
        "Terciario" : int("6"),
        "Universitario" : int("7"),
        "Posgrado Univ." : int("8"),
        "Educación especial (discapacitado)" : int("9"),
    },
    "CH13": {
        "Sí" : int("1"),
        "No" : int("2"),
        "Ns./Nr." : int("9")
    },
    "CH14": {
        "Ninguno" : int("00"),
        "Primero" : int("01"),
        "Segundo" : int("02"),
        "Tercero" : int("03"),
        "Cuarto" : int("04"),
        "Quinto" : int("05"),
        "Sexto" : int("06"),
        "Séptimo" : int("07"),
        "Octavo" : int("08"),
        "Noveno" : int("09"),
    },
    "CH15": {
        "En esta localidad": 1,
        "En otra localidad de esta provincia": 2,
        "En otra provincia": 3,
        "En un país limítrofe": 4,
        "En otro país": 5,
        "Ns./Nr.": 9,
    },
    "CH16": {
        "En esta localidad": 1,
        "En otra localidad de esta provincia": 2,
        "En otra provincia": 3,
        "En un país limítrofe": 4,
        "En otro país": 5,
        "No había nacido": 6,
        "Ns./Nr.": 9,
    },
    "NIVEL_ED": {
        "Primaria Incompleta (incluye educación especial)" : 1,
        "Primaria Incompleta": 1,
        "Primaria Completa": 2,
        "Secundaria Incompleta": 3,
        "Secundaria Completa": 4,
        "Superior Universitaria Incompleta": 5,
        "Superior Universitaria Completa": 6,
        "Sin instrucción": 7,
        "Ns./Nr.": 9,
    },
    "ESTADO": {
        "Entrevista individual no realizada": 0,
        "Ocupado": 1,
        "Desocupado": 2,
        "Inactivo": 3,
        "Menor de 10 años": 4,
    },
    "CAT_OCUP": {
        "Patrón": 1,
        "Cuenta propia": 2,
        "Obrero o empleado": 3,
        "Trabajador familiar sin remuneración": 4,
        "Ns./Nr.": 9,
    },
    "CAT_INAC": {
        "Jubilado / Pensionado": 1,
        "Rentista": 2,
        "Estudiante": 3,
        "Ama de casa": 4,
        "Menor de 6 años": 5,
        "Discapacitado": 6,
        "Otros": 7,
    },
    "PP02C1": {
        "Sí": 1,
        "No": 2,
    },
    "PP02C2": {
        "Sí": 1,
        "No": 2,
    },
    "PP02C3": {
        "Sí": 1,
        "No": 2,
    },
    "PP02C4": {
        "Sí": 1,
        "No": 2,
    },
    "PP02C5": {
        "Sí": 1,
        "No": 2,
    },
    "PP02C6": {
        "Sí": 1,
        "No": 2,
    },
    "PP02C7": {
        "Sí": 1,
        "No": 2,
    },
    "PP02C8": {
        "Sí": 1,
        "No": 2,
    },
    "PP02E": {
        "Está suspendido": 1,
        "Ya tiene trabajo asegurado": 2,
        "Se cansó de buscar trabajo": 3,
        "Hay poco trabajo en esta época del año": 4,
        "Por otras razones": 5,
    },
    "PP02H": {
        "Sí": 1,
        "No": 2,
    },
    "PP02I": {
        "Sí": 1,
        "No": 2,
    },
    "PP03C": {
        "Un sólo empleo / ocupación / actividad": 1,
        "Más de un empleo / ocupación / actividad": 2,
    },
    
    "PP03G": {
        "Sí": 1,
        "No": 2,
    },
    "PP03H": {
        "Podía trabajarlas esa semana": 1,
        "Podía empezar a trabajarlas en dos semanas a más tardar": 2,
        "No podía trabajar más horas": 3,
        "Ns./Nr.": 9,
    },
    "PP03I": {
        "Sí": 1,
        "No": 2,
        "Ns./Nr.": 9,
    },
    "PP03J": {
        "Sí": 1,
        "No": 2,
        "Ns./Nr.": 9,
    },
    "INTENSI": {
        "Subocupación horaria Demandante": 1,
        "Subocupación horaria No Demandante": 2,
        "Ocupación plena": 3,
        "Sobreocupación horaria": 4,
        "Ocupado que no trabajó en la semana": 5,
        "Ns./Nr.": 9,
    },
    "PP04A": {
        "Estatal": 1,
        "Privada": 2,
        "Otro tipo": 3,
    },
    
    "PP04B1": {
        "Casa de familia": 1,
    },
    "PP04C": {
        "1 persona": 1,
        "2 personas": 2,
        "3 personas": 3,
        "4 personas": 4,
        "5 personas": 5,
        "6 a 10 personas": 6,
        "11 a 25 personas": 7,
        "26 a 40 personas": 8,
        "41 a 100 personas": 9,
        "101 a 200 personas": 10,
        "201 a 500 personas": 11,
        "Más de 500 personas": 12,
        "Ns./Nr.": 99,
    },
    "PP04C99": {
        "Hasta 5": 1,
        "De 6 a 40": 2,
        "Más de 40": 3,
        "Ns./Nr.": 9,
    },
    "PP04G": {
        "En un local / oficina / establecimiento / negocio / taller / chacra / finca": 1,
        "En puesto o kiosco fijo callejero": 2,
        "En vehículos: bicicleta / moto / autos / barcos / botes": 3,
        "En vehículo para transporte de personas y mercaderías": 4,
        "En obras en construcción, de infraestructura, minería o similares": 5,
        "En esta vivienda (sin lugar exclusivo)": 6,
        "En la vivienda del socio o del patrón": 7,
        "En el domicilio / local de los clientes": 8,
        "En la calle / espacios públicos / ambulante / de casa en casa / puesto móvil callejero": 9,
        "En otro lugar": 10,
    },
    "PP05C_1": {
        "Propio (del negocio)": 1,
        "Prestado / alquilado": 2,
        "No tiene": 3,
    },
    "PP05C_2": {
        "Propio (del negocio)": 1,
        "Prestado / alquilado": 2,
        "No tiene": 3,
    },
    "PP05C_3": {
        "Propio (del negocio)": 1,
        "Prestado / alquilado": 2,
        "No tiene": 3,
    },
    "PP05E": {
        "Sí": 1,
        "No": 2,
    },
    "PP05F": {
        "Un sólo cliente": 6,
        "Distintos clientes": 7,
    },
    "PP05H": {
        "Menos de 1 mes": 1,
        "De 1 a 3 meses": 2,
        "Más de 3 a 6 meses": 3,
        "Más de 6 meses a 1 año": 4,
        "Más de 1 a 5 años": 5,
        "Más de 5 años": 6,
        "Ns./Nr.": 9,
    },
    "PP06A": {
        "Sí": 1,
        "No": 2,
    },
    "PP06H": {
        "Sí": 1,
        "No": 2,
    },
    "PP07A": {
        "Menos de 1 mes": 1,
        "1 a 3 meses": 2,
        "Más de 3 a 6 meses": 3,
        "Más de 6 a 12 meses": 4,
        "Más de 1 a 5 años": 5,
        "Más de 5 años": 6,
        "Ns./Nr.": 9,
    },
    "PP07C": {
        "Sí": 1,
        "No": 2,
        "Ns./Nr.": 9,
    },
    "PP07D": {
        "Sólo fue esa vez / sólo cuando lo llaman": 1,
        "Hasta 3 meses": 2,
        "Más de 3 a 6 meses": 3,
        "Más de 6 a 12 meses": 4,
        "Más de 1 año": 5,
        "Ns./Nr.": 9,
    },
    "PP07D": {
        "Un plan de empleo": 1,
        "Un período de prueba": 2,
        "Una beca / pasantía / aprendizaje": 3,
        "Ninguno de éstos": 4,
    },
    "PP07F1": {
        "Sí": 1,
        "No": 2,
    },
    "PP07F2": {
        "Sí": 1,
        "No": 2,
    },
    "PP07F3": {
        "Sí": 1,
        "No": 2,
    },
    "PP07F4": {
        "Sí": 1,
        "No": 2,
    },
    "PP07F5": {
        "Sí": 5,
    },
    "PP07G1": {
        "Sí": 1,
        "No": 2,
    },
    "PP07G2": {
        "Sí": 1,
        "No": 2,
    },
    "PP07G3": {
        "Sí": 1,
        "No": 2,
    },
    "PP07G4": {
        "Sí": 1,
        "No": 2,
    },
    "PP07G59": {
        "Sí": 1,
    },
    "PP07H": {
        "Sí": 1,
        "No": 2,
    },
    "PP07I": {
        "Sí": 1,
        "No": 2,
    },
    "PP07J": {
        "De día (mañana / tarde)": 1,
        "De noche": 2,
        "De otro tipo (rotativo, día y noche, guardias con franco)": 3,
    },
    "PP07K": {
        "Le dan recibo con sello / membrete / firma del empleador": 1,
        "Le dan un papel / recibo sin nada": 2,
        "Entrega una factura": 3,
        "No le dan ni entrega nada": 4,
        "No cobra, es trabajador sin pago / ad-honorem": 5,
    },
    "PP09A": {
        "Ciudad de Buenos Aires": 1,
        "Partidos del GBA": 2,
        "Ambos": 3,
        "En otro lugar": 4,
    },
    "PP09B": {
        "Sí": 1,
        "No": 2,
    },
    "PP09C": {
        "En otro lugar de esta provincia": 1,
        "En otra provincia": 2,
        "En otro país": 3,
    },
    "PP10A": {
        "Menos de 1 mes": 1,
        "De 1 a 3 meses": 2,
        "Más de 3 a 6 meses": 3,
        "Más de 6 a 12 meses": 4,
        "Más de 1 año": 5,
    },
    "PP10C": {
        "Sí": 1,
        "No": 2,
    },
    "PP10D": {
        "Sí": 1,
        "No": 2,
    },
    "PP10E": {
        "Menos de 1 mes": 1,
        "De 1 a 3 meses": 2,
        "Más de 3 a 6 meses": 3,
        "Más de 6 a 12 meses": 4,
        "Más de 1 a 3 años": 5,
        "Más de 3 años": 6,
    },
    "PP11A": {
        "Estatal": 1,
        "Privada": 2,
        "Otro tipo": 3,
    },
    "PP11B1": {
        "Casa de familia": 1,
    },
    "PP11B2": "cantidad de casas donde trabaja",
    "PP11B3_MES": "meses trabajando allí",
    "PP11B3_ANO": "años trabajando allí",
    "PP11B3_DIA": "días trabajando allí",
    "PP11C": {
        "1 persona": 1,
        "2 personas": 2,
        "3 personas": 3,
        "4 personas": 4,
        "5 personas": 5,
        "6 a 10 personas": 6,
        "11 a 25 personas": 7,
        "26 a 40 personas": 8,
        "41 a 100 personas": 9,
        "101 a 200 personas": 10,
        "201 a 500 personas": 11,
        "Más de 500 personas": 12,
        "Ns./Nr.": 99,
    },
    "PP11C99": {
        "Hasta 5": 1,
        "De 6 a 40": 2,
        "Más de 40": 3,
        "Ns./Nr.": 9,
    },
   
    "PP11L" : {
        "falta de clientes / clientes que no pagan" : 1,
        "falta de capital / equipamiento" : 2,
        "trabajo estacional" : 3,
        "tenía gastos demasiado altos" : 4,
        "otras causas laborales (especificar)" :5,
        "jubilación / retiro" : 6,
        "causas personales (matrimonio, embarazo, cuidado de hijos o familiar, estudio, enfermedad)" : 7,
    },
    "PP11L1" : {
        "...una changa, trabajo transitorio, por tarea u obra, suplencia, etc.?" : 1,
        "...un trabajo permanente, fijo, estable, de planta, etc.?" : 2,
        "Ns./Nr." : 3,
    },
    "PP11M" : {
        "...un plan de empleo?" : 1,
        "...un período de prueba?" : 2,
        "...otro tipo de trabajo?" : 3,
    },
    "PP11N": {
        "Sí": 1,
        "No": 2,
        "Ns./Nr.": 9,
    },
    "PP11O": {
        "Despido / cierre (quiebra / venta / traslado de la empresa, reestructuración o recorte de personal / falta de ventas o clientes)": 1,
        "Por retiro voluntario del sector público": 2,
        "Por jubilación": 3,
        "Fin de trabajo temporario / estacional": 4,
        "Le pagaban poco / no le pagaban": 5,
        "Malas relaciones laborales / malas condiciones de trabajo (insalubre, cambios de horarios, etc.)": 6,
        "Renuncia obligada / pactada": 7,
        "Otras causas laborales (especificar)": 8,
        "Por razones personales (matrimonio, embarazo, cuidado de hijos o familia, estudio, enfermedad)": 9,
    },
    "PP11P": {
        "Sí": 1,
        "No": 2,
        "Ns./Nr.": 9,
    },
    "PP11Q": {
        "Sí": 1,
        "No": 2,
        "Ns./Nr.": 9,
    },
    "PP11R": {
        "Sí": 1,
        "No": 2,
    },
    "PP11S": {
        "Sí": 1,
        "No": 2,
    },
    "PP11T": {
        "Sí": 1,
        "No": 2,
        "Ns./Nr.": 9,
    },
    
    "CH15_COD" : {
        "En otra provincia (Ver Códigos Geográficos de Provincias) " : 3,
        "En un país limítrofe (Ver Códigos Geográficos de Países y Territorios Vinculados) " : 4,
        "En otro país (Ver Códigos Geográficos de Países y Territorios Vinculados) " : 5,
    },
    
    "CH16_COD" : {
        "En otra provincia (Ver Códigos Geográficos de Provincias) " : 3,
        "En un país limítrofe (Ver Códigos Geográficos de Países y Territorios Vinculados) " : 4,
        "En otro país (Ver Códigos Geográficos de Países y Territorios Vinculados) " : 5,
    },
    
    "PP06E": {
        "Sí": 1,
        "No": 2,
    },
    "PP07E": {
        "Un plan de empleo": 1,
        "Un período de prueba": 2,
        "Una beca / pasantía / aprendizaje": 3,
        "Ninguno de éstos": 4,
    },
    "PP07G_59": {
        "Sí": 1,
    },   
}

diccionario_hogar = {
    "CODUSU" : "código",
    "NRO_HOGAR" : "número de hogar",
    "REALIZADA" : {
        "Sí" : 1,
        "No" : 2,
    },
    "ANO" : "año",
    "TRIMESTRE" : {
        "1er. Trimestre" : 1,
        "2do. Trimestre" : 2,
        "3er. Trimestre" : 3,
        "4to. Trimestre" : 4,
    },
    "REGION" : {
        "Gran Buenos Aires" : 1,
        "NOA" : 40,
        "NEA" : 41,
        "Cuyo" : 42,
        "Pampeana" : 43,
        "Patagónica" : 44,
    },
    "MAS_500" : {
        "N" : 0,
        "S" : 1,
    },
    "AGLOMERADO" : {
        "Gran La Plata" : 2,
        "Bahía Blanca - Cerri" : 3,
        "Gran Rosario" : 4,
        "Gran Santa Fé" : 5,
        "Gran Paraná" : 6,
        "Posadas" : 7,
        "Gran Resistencia" : 8,
        "Cdro. Rivadavia – Rada Tilly" : 9,
        "Gran Mendoza" : 10,
        "Corrientes" : 12,
        "Gran Córdoba" : 13,
        "Concordia" : 14,
        "Formosa" : 15,
        "Neuquén – Plottier" : 17,
        "S.del Estero - La Banda" : 18,
        "Jujuy - Palpalá" : 19,
        "Río Gallegos" : 20,
        "Gran Catamarca" : 22,
        "Salta" : 23,
        "La Rioja" : 25,
        "San Luis - El Chorrillo" : 26,
        "Gran San Juan" : 27,
        "Gran Tucumán - T. Viejo" : 29,
        "Santa Rosa - Toay" : 30,
        "Ushuaia - Río Grande" : 31,
        "Ciudad de Buenos Aires" : 32,
        "Partidos del GBA" : 33,
        "Mar del Plata - Batán" : 34,
        "Río Cuarto" : 36,
    },
    "PONDERA" : "ponderador",
    "IV1" : {
        "Casa" : 1,
        "Departamento" : 2,
        "Pieza de inquilinato" : 3,
        "Pieza en hotel / pensión" : 4,
        "Local no construido para habitación" : 5,
        "Otros" : 6,
    },
    "NRO_HOGAR" : "número de hogar",
    "REALIZADA" : {
        "Sí" : 1,
        "No" : 2,
    },
    "ANO" : "año",
    "TRIMESTRE" : {
        "1er. Trimestre" : 1,
        "2do. Trimestre" : 2,
        "3er. Trimestre" : 3,
        "4to. Trimestre" : 4,
    },
    "IV3" : {
        "Mosaico / baldosa / madera / cerámica / alfombra" : 1,
        "Cemento / ladrillo fijo" : 2,
        "Ladrillo suelto / tierra" : 3,
        "Otro" : 4,
    },  
    "IV4" : {
        "Membrana / cubierta asfáltica" : 1,
        "Baldosa / losa sin cubierta" : 2,
        "Pizarra / teja" : 3,
        "Chapa de metal sin cubierta" : 4,
        "Chapa de fibrocemento / plástico" : 5,
        "Chapa de cartón" : 6,
        "Caña / tabla / paja con barro / paja sola" : 7,
        "N/S. Depto en propiedad horizontal" : 9,
    },
    "IV5" : {
        "Sí" : 1,
        "No" : 2,
    },
    "IV6" : {
        "Por cañería dentro de la vivienda" : 1,
        "Fuera de la vivienda pero dentro del terreno" : 2,
        "Fuera del terreno" : 3,
    },
    "IV7" : {
        "Red pública (agua corriente)" : 1,
        "Perforación con bomba a motor" : 2,
        "Perforación con bomba manual" : 3,
        "Otra fuente" : 4,
    },
    "IV8" : {
        "Sí" : 1,
        "No" : 2,
    },
    "IV9" : {
        "Dentro de la vivienda" : 1,
        "Fuera de la vivienda pero dentro del terreno" : 2,
        "Fuera del terreno" : 3,
    },
    "IV10" : {
        "Inodoro con botón / mochila / cadena y arrastre de agua" : 1,
        "Inodoro sin botón / cadena y con arrastre de agua (a balde)" : 2,
        "Letrina (sin arrastre de agua)" : 3,
    },
    "IV11" : {
        "A red pública (cloaca)" : 1,
        "A cámara séptica y pozo ciego" : 2,
        "Sólo a pozo ciego" : 3,
        "A hoyo / excavación en la tierra" : 4,
    },
    "IV12_1" : {
        "Sí" : 1,
        "No" : 2,
    },
    "IV12_2" : {
        "Sí" : 1,
        "No" : 2,
    },
    "IV12_3" : {
        "Sí" : 1,
        "No" : 2,
    },
   
    "II3" : {
        "Sí" : 1,
        "No" : 2,
    },
    "II3_1" : {
        "Sí" : 1,
        "No" : 2,
    },
    "II4_1" : {
        "Sí" : 1,
        "No" : 2,
    },
    "II4_2" : {
        "Sí" : 1,
        "No" : 2,
    },
    "II4_3" : {
        "Sí" : 1,
        "No" : 2,
    },
    "II5" : {
        "Sí" : 1,
        "No" : 2,
    },
    
    "II6" : {
        "Sí" : 1,
        "No" : 2,
    },
    
    "II7" : {
        "Propietario de la vivienda y el terreno" : 1,
        "Propietario de la vivienda solamente" : 2,
        "Inquilino / arrendatario de la vivienda" : 3,
        "Ocupante por pago de impuestos / expensas" : 4,
        "Ocupante en relación de dependencia" : 5,
        "Ocupante gratuito (con permiso)" : 6,
        "Ocupante de hecho (sin permiso)" : 7,
        "Está en sucesión" : 8,
        "Otra situación" : 9,
    },
    
    "II8" : {
        "Gas de red" : 1,
        "Gas de tubo / garrafa" : 2,
        "Kerosene / leña / carbón" : 3,
        "Otro" : 4,
    },
    
    "II9" : {
        "Uso exclusivo del hogar" : 1,
        "Compartido con otro/s hogar/es de la misma vivienda" : 2,
        "Compartido con otra/s vivienda/s" : 3,
        "No tiene baño" : 4,
    },
    "V1" : {
        "Sí" : 1,
        "No" : 2,
    },
    "V2" : {
        "Sí" : 1,
        "No" : 2,
    },
    "V21" : {
        "Sí" : 1,
        "No" : 2,
    },
    "V22" : {
        "Sí" : 1,
        "No" : 2,
    },
    "V3" : {
        "Sí" : 1,
        "No" : 2,
    },
    "V4" : {
        "Sí" : 1,
        "No" : 2,
    },
    "V5" : {
        "Sí" : 1,
        "No" : 2,
    },
    "V6" : {
        "Sí" : 1,
        "No" : 2,
    },
    "V7" : {
        "Sí" : 1,
        "No" : 2,
    },
    "V8" : {
        "Sí" : 1,
        "No" : 2,
    },
    "V9" : {
        "Sí" : 1,
        "No" : 2,
    },
    "V10" : {
        "Sí" : 1,
        "No" : 2,
    },
    "V11" : {
        "Sí" : 1,
        "No" : 2,
    },
    "V12" : {
        "Sí" : 1,
        "No" : 2,
    },
    "V13" : {
        "Sí" : 1,
        "No" : 2,
    },
    "V14" : {
        "Sí" : 1,
        "No" : 2,
    },
    "V15" : {
        "Sí" : 1,
        "No" : 2,
    },
    "V16" : {
        "Sí" : 1,
        "No" : 2,
    },
    "V17" : {
        "Sí" : 1,
        "No" : 2,
    },
    "V18" : {
        "Sí" : 1,
        "No" : 2,
    },
    "V19_A" : {
        "Sí" : 1,
        "No" : 2,
    },
    "V19_B" : {
        "Sí" : 1,
        "No" : 2,
    },
}